global:
  region: KR
  timeout: 30000
# dragon config
dragon:
  language: zh_CN
  url:
    cdn: http://ddragon.leagueoflegends.com/cdn/dragontail-{0}.tgz
    realm: https://ddragon.leagueoflegends.com/realms/{0}.json
    version: https://ddragon.leagueoflegends.com/api/versions.json
  directory: D:/lol
# api config
api:
  rate: 0.83333
  tokens:
    - username: Kingen4391
      region: BR
      key: RGAPI-2dc78e8f-e963-4e9e-a4e4-6d98ca1d558e
    - username: Kingen4392
      region: ENUE
      key: RGAPI-62a4025f-22ca-409a-b0f8-3c27533d0183
    - username: Kingen4393
      region: EUW
      key: RGAPI-dff9ed90-06da-4eab-914f-3bf471d5f1b5
    - username: Kingen4394
      region: JP
      key:
    - username: Kingen4395
      region: NA
      key: RGAPI-c20908c3-7bdd-4cf3-9508-79e254996e6f
    - username: Kingen4396
      region: OCE
      key: RGAPI-d6e2eaf1-134f-4fa7-abff-6b5e84a5e8a5
    - username: Kingen4397
      region: NA
      key: RGAPI-0244f774-348d-4a29-bd36-290d102bd00f
    - username: Kingen4398
      region: NA
      key: RGAPI-e20edb00-a358-43e5-b781-5a9a6f28200c
    - username: Kingen4399
      region: OCE
      key: RGAPI-c772049e-fcda-4a03-af90-6be0a07b6861
    - username: Kingen4400
      region: RU
      key: RGAPI-558bbe82-27e7-4b6f-99f6-8c46c101d3d0
    - username: Kingen4401
      region: TR
      key: RGAPI-2327afe7-2ee5-4725-a312-52f1e5df81f4
    - username: knightmare2094
      region: NA
      key: RGAPI-3439eca4-48a1-42aa-917a-7fff00b8cd9a