global:
  region: JP
  timeout: 30000
# dragon config
dragon:
  language: zh_CN
  url:
    cdn: http://ddragon.leagueoflegends.com/cdn/dragontail-{0}.tgz
    realm: https://ddragon.leagueoflegends.com/realms/{0}.json
    version: https://ddragon.leagueoflegends.com/api/versions.json
  directory: D:/lol
# api config
api:
  rate: 0.83333
  tokens:
    - username: Kingen4391
      region: BR
      key: RGAPI-2dc78e8f-e963-4e9e-a4e4-6d98ca1d558e
    - username: Kingen4392
      region: ENUE
      key: RGAPI-62eb9f5d-9301-4500-8a30-59d233731c39
    - username: Kingen4393
      region: EUW
      key: RGAPI-9f51d9a6-c28d-4625-b4e4-ba9afed23adc
    - username: Kingen4394
      region: JP
      key:
    - username: Kingen4395
      region: NA
      key: RGAPI-0f6990d2-5536-45ed-8e48-05e9ffe84342
    - username: Kingen4396
      region: OCE
      key: RGAPI-8c568d2e-e328-4b79-9fb4-96ce1a5ce919
    - username: Kingen4397
      region: NA
      key: RGAPI-11639d5b-2466-491f-a2e3-2d436e6af2ae
    - username: Kingen4398
      region: NA
      key: RGAPI-b25e1b82-8abe-4411-b9f5-446051a5478d
    - username: Kingen4399
      region: OCE
      key: RGAPI-fafe76b5-de31-42b2-9274-55b84bca58d6
    - username: Kingen4400
      region: RU
      key: RGAPI-71ee369d-93db-4285-9530-32a39cd2d6b8
    - username: Kingen4401
      region: TR
      key: RGAPI-c9c6d14f-09e3-4275-a155-2c6cc86063be
    - username: knightmare2094
      region: NA
      key: RGAPI-43ad21e5-1eb9-4178-9f99-764a2f58db33