task:
  corePoolSize: 10
  maxPoolSize: 100
  queueCapacity: 10
  keepAliveSeconds: 300
# cron for scheduler
cron:
  event:
    summoner: 0/2 * * * * ?
    match: 0/6 * * * * ?
  update:
    summoner: 0 0 0 1/1 * ?
    match: 0/6 * * * * ?
  share:
    version: 0 0 0 1/1 * ?
    shard: 0 0 0 1/1 * ?