task:
  corePoolSize: 10
  maxPoolSize: 100
  queueCapacity: 10
  keepAliveSeconds: 300
# cron for scheduler
cron:
#  event:
  #      summoner: 0 0/10 * * * ?
  #      match: 0 0/30 * * * ?
  #  update:
  #    summoner: 0 * * 1/1 * ?
  #    match: 0 0/30 * * * ?
  share:
    version: 0 0 * 1/1 * ?
    shard: 0 0 0 1/1 * ?
    featured: 0 0 0 1/1 * ?
  event:
    summoner: 0 0 0 * * ?
    match: 0 0 0 * * ?
  update:
    summoner: 0 0 0 1/1 * ?
    match: 0 0 0 * * ?