spring:
  freemarker:
    template-loader-path: classpath:templates/lol, classpath:/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/%s?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 2787
  resources:
    static-locations: classpath:/static/, classpath:/
server:
  port: 8090
logging:
  config: classpath:config/logback.xml