spring:
  freemarker:
    template-loader-path: classpath:templates/lol, classpath:/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  datasource:
    name: mysql.na
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lol?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 4787
  redis:
    database: 0
    host: localhost
    port: 6380
    password:
    timeout: 1000
    jedis:
      pool:
        max-idle: 10
        max-active: 200
        max-wait: 1
        min-idle: 0
  resources:
    static-locations: classpath:/static/, classpath:/
  data:
    mongodb:
      uri: mongodb://localhost/lol
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: wsg.lol.pojo.dmo
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: wsg.lol.dao.mybatis.typeHandler
server:
  port: 8090
logging:
  config: classpath:config/logback.xml