-- 战区
CREATE TABLE l_league
(
  LEAGUE_ID VARCHAR(50) COMMENT '主键',
  NAME      VARCHAR(32) COMMENT '战区名称',
  TIER      TINYINT COMMENT '段位',
  QUEUE     TINYINT COMMENT '排位队列',
  CONSTRAINT L_LEAGUE_PK PRIMARY KEY (LEAGUE_ID)
);

-- 个人排位
CREATE TABLE l_item
(
  ID            INT AUTO_INCREMENT COMMENT '主键',
  SUMMONER_ID   VARCHAR(63) COMMENT '召唤师ID',
  LEAGUE_ID     VARCHAR(50) COMMENT '战区ID',
  SUMMONER_NAME VARCHAR(32) COMMENT '召唤师名',
  `RANK`        TINYINT COMMENT '小段位',
  LEAGUE_POINTS INT COMMENT '胜点',
  WINS          INT COMMENT '胜场',
  LOSSES        INT COMMENT '负场',
  VETERAN       TINYINT(1) COMMENT '是否老兵',
  INACTIVE      TINYINT(1) COMMENT '？？？',
  FRESH_BLOOD   TINYINT(1) COMMENT '是否新兵',
  HOT_STREAK    TINYINT(1) COMMENT '是否连胜',
  SERIES_TARGET INT COMMENT '晋级赛目标胜场',
  SERIES_WINS   INT COMMENT '晋级赛胜场',
  SERIES_LOSSES INT COMMENT '晋级赛负场',
  CONSTRAINT L_ITEM_PK PRIMARY KEY (ID),
  CONSTRAINT L_ITEM_FK_SUMMONER FOREIGN KEY (SUMMONER_ID) REFERENCES s_summoner (ID),
  CONSTRAINT L_ITEM_FK_LEAGUE FOREIGN KEY (LEAGUE_ID) REFERENCES l_league (LEAGUE_ID)
);

-- 位置排位
CREATE TABLE l_position
(
  ID            INT AUTO_INCREMENT COMMENT '主键',
  SUMMONER_ID   VARCHAR(63) COMMENT '召唤师ID',
  QUEUE_TYPE    TINYINT COMMENT '排位队列，目前仅限单双排',
  POSITION      TINYINT COMMENT '位置，中上射野辅',
  SUMMONER_NAME VARCHAR(32) COMMENT '召唤师名称',
  LEAGUE_ID     VARCHAR(50) COMMENT '战区ID，默认00000',
  LEAGUE_NAME   VARCHAR(32) COMMENT '战区名称，默认为空',
  TIER          TINYINT COMMENT '段位，目前不支持顶尖段位',
  DIVISION      TINYINT COMMENT '小段位',
  LEAGUE_POINTS INT COMMENT '胜点',
  WINS          INT COMMENT '胜场',
  LOSSES        INT COMMENT '负场',
  VETERAN       TINYINT(1) COMMENT '是否老兵',
  INACTIVE      TINYINT(1) COMMENT '？？？',
  FRESH_BLOOD   TINYINT(1) COMMENT '是否新兵',
  HOT_STREAK    TINYINT(1) COMMENT '是否连胜',
  SERIES_TARGET INT COMMENT '晋级赛目标胜场',
  SERIES_WINS   INT COMMENT '晋级赛胜场',
  SERIES_LOSSES INT COMMENT '晋级赛负场',
  CONSTRAINT L_POSITION_PK PRIMARY KEY (ID),
  CONSTRAINT L_POSITION_FK_SUMMONER FOREIGN KEY (SUMMONER_ID) REFERENCES s_summoner (ID)
);