-- 比赛记录
CREATE TABLE m_match
(
  GAME_ID        BIGINT COMMENT '主键',
  GAME_CREATION  TIMESTAMP COMMENT '开始时间',
  GAME_DURATION  INT COMMENT '时长，单位：s',
  GAME_VERSION   VARCHAR(32) COMMENT '游戏版本',
  GAME_MODE      TINYINT COMMENT '游戏模式',
  GAME_TYPE      TINYINT COMMENT '游戏类型',
  SEASON_ID      TINYINT COMMENT '赛季',
  QUEUE_ID       SMALLINT COMMENT '游戏队列',
  PLATFORM_ID    TINYINT COMMENT '平台',
  MAP_ID         TINYINT COMMENT '地图',
  FRAME_INTERVAL INT COMMENT '事件计算间隔，单位：ms',
  CONSTRAINT M_MATCH_PK PRIMARY KEY (GAME_ID)
);

-- 比赛参与者
CREATE TABLE m_participant
(
  ID                           BIGINT AUTO_INCREMENT COMMENT '主键',
  GAME_ID                      BIGINT COMMENT '比赛ID',
  PARTICIPANT_ID               INT COMMENT '参与者ID',
  SUMMONER_ID                  VARCHAR(63) COMMENT '召唤师ID',
  CHAMPION_ID                  INT COMMENT '使用的英雄ID',
  TEAM_ID                      SMALLINT COMMENT '100 for blue side. 200 for red side.',
  LANE                         TINYINT COMMENT '分路',
  ROLE                         TINYINT COMMENT '角色',
  SPELL1_ID                    VARCHAR(32) COMMENT '召唤师技能ID',
  SPELL2_ID                    VARCHAR(32) COMMENT '召唤师技能ID',
  HIGHEST_ACHIEVED_SEASON_TIER TINYINT COMMENT '赛季最高段位',
  -- wsg TIMELINE, STAT
  CONSTRAINT M_PARTICIPANT_PK PRIMARY KEY (ID),
  CONSTRAINT M_PARTICIPANT_FK_GAME FOREIGN KEY (GAME_ID) REFERENCES m_match (GAME_ID),
  CONSTRAINT M_PARTICIPANT_FK_SUMMONER FOREIGN KEY (SUMMONER_ID) REFERENCES s_summoner (ID)
  #   CONSTRAINT M_PARTICIPANT_FK_CHAMPION FOREIGN KEY (CHAMPION_ID) REFERENCES c_champion (ID),
  #   CONSTRAINT M_PARTICIPANT_FK_SPELL1 FOREIGN KEY (SPELL1_ID) REFERENCES c_spell (ID),
  #   CONSTRAINT M_PARTICIPANT_FK_SPELL2 FOREIGN KEY (SPELL2_ID) REFERENCES c_spell (ID)
);